
# Resource Group for project-caf
# Generated by Code Pusher

resource "azurerm_resource_group" "project_caf" {
  name     = "rg-project-caf"
  location = "eastus"
  
  tags = {
    
    "Environment" = "Production"
    
    "Project" = "project-caf"
    
    "CreatedBy" = "CodePusher"
    "CreatedAt" = timestamp()
  }

  lifecycle {
    ignore_changes = [tags["CreatedAt"]]
  }
}